apiVersion: apps/v1
kind: Deployment
metadata:
  name: pychat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pychat
  template:
    metadata:
      labels:
        app: pychat
    spec:
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/jenkins-project-388812/dockerimages/pychat
        #image: pychat
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: DB_HOST
          value: db-api-service
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
