# This workflow build and push a Docker container to Google Artifact Registry and deploy it on Cloud Run when a commit is pushed to the "main" branch
#
# Overview:
#
# 1. Authenticate to Google Cloud
# 2. Authenticate Docker to Artifact Registry
# 3. Build a docker container
# 4. Publish it to Google Artifact Registry
# 5. Deploy it to Cloud Run
#

name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "dev" ]

env:
  PROJECT_ID: jenkins-project-388812 # TODO: update Google Cloud project id
  SERVICE: pychat # TODO: update Cloud Run service name
  REGION: us-central1 # TODO: update Cloud Run service region
  IMAGE: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CLOUDRUN_JSON_KEY }}'

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CLOUDRUN_JSON_KEY }}
          
      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.IMAGE }}" ./
          docker push "${{ env.IMAGE }}"

      - name: Prepare pychat.yml
        run: |
          sed -i 's/{{ SERVICE }}/${{ env.SERVICE }}/g' ${{ GITHUB_WORKSPACE }}/pychat.yml
          sed -i 's/{{ REGION }}/${{ env.REGION }}/g' ${{ GITHUB_WORKSPACE }}/pychat.yml
          sed -i 's/{{ PORT }}/${{ env.PORT }}/g' ${{ GITHUB_WORKSPACE }}/pychat.yml
          sed -i 's/{{ IMAGE }}/${{ env.IMAGE }}/g' ${{ GITHUB_WORKSPACE }}/pychat.yml

      # END - Docker auth and build
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          metadata: ${{ GITHUB_WORKSPACE }}/pychat.yml

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
