name: Testing customaction

on:
  push:
    branches: ["test-customaction"]

jobs:
  test:
    # Add 'id-token' with the intended permissions for workload identity federations
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test
        uses: ./msteams-notifications
        with:
          facts: |
            - clave: test
            - test2: test2
            - test3: test3
            - test4: test4
            - test5: test5
